### ISSUE TITLE
Add the badge to the README.md

### ISSUE THREAD

**Issue by Adron** [ThrashingCode/coder-swap#2]
[![Stories in Ready](https://badge.waffle.io/ThrashingCode/coder-swap.png?label=ready&title=Ready)](http://waffle.io/ThrashingCode/coder-swap)

**Comment by Keartida** [comment]
Added the change in commit 9b31dd9adc63f46e6d6613f1fdf46ee4998262f1 and submitted the pull request here https://github.com/ThrashingCode/coder-swap/pull/11
